# basic concepts

## generating theories and test them

### Theory

general prediction ans statements from logical deduction, experience and observations, e.g., Social role theory is a concept in sociology and social psychology that explains how individuals behave based on the roles they occupy in society, such as parent, teacher, or leader. These roles come with specific expectations and norms that guide behavior in various contexts.

### hypothesis

scientific statements that are produced based on theory, which are generally measurable and testable. e..g, from social role theory, we predict that women, following their gender role, are less likely to apply for management role.

-   reject of the hypothesis: falsification.

source: discovering statistics with R, 1.4

## level of measurement

-   categorical variable
    -   e.g., names of species: human, dog, cat
    -   binary variable
        -   yes, no
        -   1, 0
    -   nominal var
        -   e.g., use number to denote categories (multiple possibilities)
-   ordinal var
    -   logically ordered categories, e.g., gold, silver, bronze medal
-   continuous var
    -   interval var
        -   5-point likert scale
    -   ratio var
        -   e.g., twice as much helpful, etc
        -   must have a valid, meaningful 0 point
    -   discreet var
        -   where one can only take up certain values (e.g., only 1-5 in a 5-point likert scale), not every numerical value possible

source: discovering statistics with R, 1.5.1.2

## validity and reliability
- (criterion) Validity
	- if an instrument measures what is designs to measure
		- e.g., is this survey question fully capturing people's amount of DMU?
	- content validity
		- the degree to which individual items represent the construct being measured, and cover the full range of the construct
- Reliability
	- the ability of the measure to produce the same results under the same conditions (replicability / robustness?)
	
source: discovering statistics with R, 1.5.3

## correlational and experimental research
### correlational / cross-sectional research
- notion: observe what naturally happens in the world without directly interfering with it, typically work on the phenomena that we cannot easily manipulate
- caveat: problem of proving causal relationship
- stat method: typically measured with regression, correlation
### experimental
- notion: manipulate certain variable and observe the effect on another
- stat method: typically measured with ANOVA, t-test
	- But mathematically , the statistical methods mentioned above are identical
- two types of data collection 
	- between group / between subject design: different group of participants take part in each experimental condition
	- within subject / repeated measurement design: different experimental condition on the same group of participants
- two types of variation
	- systematic: created by specific experimental manipulation, e.g., doing sth to all participants in one condition but not in the other condition
	- unsystematic: random factors that exist between the experimental conditions (e.g., group character difference, time of the day) -> try to minimize this

- radomization
	- counterbalance the systematic variation
		- e.g., randomize the order of the conditions to counterbalance the practice effect

source: discovering statistics with R, 1.6.1. + 1.6.2. 

## descriptive data analysis
### frequency distribution
- normal distribution
	- skew value and kurtosis value are both 0
	- in this case, mean is 0, sd is 1
- distortion from normal distribution (plotting out histogram)
	- positively skewed (left leaning) and negatively skewed (right leaning)
	- positive kurtosis (excessively pointy) and negative kurtosis

### center of a distribution
mean, mode, and the median

### dispersion in a distribution
- range: max minus min
- quartiles
	- lower quartile
	- second quartile: median
	- upper quartile
	- interquartile: middle 50% of the data
	- a common exclusion strategy: keep the interquartile for the analysis, so to exclude extreme scores

### extrapolate to probability (1.7.4)
- researchers have calculated the probability of certain score occurring if they are fitting a perfect normal distribution
- if the data we are using is not normally distributed, we can calculate a z-score and calculate the corresponding probability
	- z-score: A z-score, or standard score, indicates how many standard deviations a raw score is from the mean of a population. It is calculated by subtracting the population mean from the raw score and dividing by the population standard deviation.
		- select the raw score
		- calculate z-score (equation in 1.7.4)
		- check in the existing table: the Smaller Portion -> that's the probability of the value to occur :)

source: discovering statistics with R, 1.7. 