---
title: "statistics for social science"
author: "Milin Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Goal of this site:

-   organize my own statistical notes mainly focusing on application for social science

-   note down new statistical concepts when reading research papers and how they can contribute to my research

    -   which highly relies on regression analysis and longitudinal data analysis to test hypothesis

The notes taken on this site are rarely my own content, i mainly take notes from following sources:

-   MA course "Multivariate Statistics" handouts by Maud Reveilhac: <https://meth.ikmz.uzh.ch/>

-   Textbooks series of "Discovering Statistics" by Andy Field: <https://discoveringstatistics.com/>

-   Statistics Tutorial by numiqo: <https://numiqo.com/tutorial/get-started>

------------------------------------------------------------------------

question marks

1.  what is a hurdle model? -\> particularly useful for data with many zero values

<!-- -->

a.  source: "Preliminary analyses revealed that there is an excess number of cases with zero exposure to alternative news in both data sets. To account for this skewed distribution of our criterion variable, we opted to use hurdle models (see Mullahy, 1986) to analyze predictors of alternative news use. " (Müller & Bach, 2021)

b.  Mullahy J (1986) Specification and testing of some modified count data models. Journal of Econometrics 33(3): 341–365.

<!-- -->

2.  what does "Locally weighted scatterplot smoothing (LOWESS) trend lines with alpha = .2." mean?
